apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring1
  template:
    metadata:
      labels:
        app: spring1
    spec:
      containers:
        - name: spring1-container
          image: kavitha142/spring1:latest
          ports:
            - containerPort: 8084
