apiVersion: v1
kind: Service
metadata:
  name: javawebcalculator-service
spec:
  selector:
    app: javawebcalculator
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8085  
  type: LoadBalancer  
